### ISSUE TITLE
error al intentar instalar en odoo v9.0

### ISSUE THREAD

**Issue by efarias** [odoo-chile/l10n_cl_chart#2]
@Danisan siguiendo con el issue cerrado en bmya/odoo-bmya-cl#6 , te dejo este traceback al intentar instalar en Odoo v9.0, aparentemente hay campos nulos que en el esquema de la BB.DD de odoo 9.0 no se admiten como nulos. En cuanto tenga un tiempo revisaré con más detalle para ver si puedo cooperar con las modificaciones para instalar en Odoo 9.0

Saludos

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 907, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 895, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1122, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4131, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4269, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/odoo/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "action_id" violates not-null constraint
DETAIL:  Failing row contains (2, 2016-03-22 00:21:04.302463, null, 10, 1, null, open, 2016-03-22 00:21:04.302463, manual, 1, null).
" while parsing /opt/odoo/addons/l10n_cl_chart/data/l10n_cl_bmya_wizard.xml:4, near
<record id="account.action_wizard_multi_chart_todo" model="ir.actions.todo">
            <field name="state">open</field>
        </record>


```

**Comment by Danisan** [comment]
Ver sobre el tema colaboración como está actualmente... no lo estamos actualizando actualmente. Igual es un issue y lo voy a dejar abierto, por si alguien que quiera resolverlo lo haga.
http://www.odoochile.org/blog/novedades-1/post/principios-para-colaborar-en-github-1#blog_content

**Comment by NicoRiquelmeCTI** [comment]
Hola, 

Se que ha pasado tiempo, pero estoy teniendo exactamente el mismo error intentando instalar el módulo, pero en la versión 12. @efarias como lo resolviste?

**Comment by chelopezlo** [comment]
Hola! Estoy teniendo el mismo problema. Alguna pista para revisarlo y resolverlo?

Saludos!!
