### ISSUE TITLE
Error al instalar modulo l10n_cl_chart odoo V9

### ISSUE THREAD

**Issue by evaldez23** [odoo-chile/l10n_cl_chart#3]
mi estimado muy buenas tarde soy estudiantes y estoy recién comenzando con odoo9 descargue uno de los módulos desarrollados por usted y tengo el siguiente problema espero que me pueda ayudar y compartir información y a su vez poder ayudar.

Chile Localization Chart Account BMyA Version -9

Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/openerp/http.py", line 680, in dispatch
result = self._call_function(*_self.params)
File "/opt/odoo/openerp/http.py", line 316, in _call_function
return checked_call(self.db, *args, *_kwargs)
File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
return f(dbname, _args, *_kwargs)
File "/opt/odoo/openerp/http.py", line 309, in checked_call
result = self.endpoint(_a, *_kw)
File "/opt/odoo/openerp/http.py", line 959, in _call_
return self.method(_args, *_kw)
File "/opt/odoo/openerp/http.py", line 509, in response_wrap
response = f(_args, *_kw)
File "/opt/odoo/addons/web/controllers/main.py", line 896, in call_button
action = self._call_kw(model, method, args, {})
File "/opt/odoo/addons/web/controllers/main.py", line 884, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
File "/opt/odoo/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/opt/odoo/openerp/modules/loading.py", line 338, in load_modules
loaded_modules, update_module)
File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
_load_data(cr, module_name, idref, mode, kind='data')
File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/opt/odoo/openerp/tools/convert.py", line 851, in convert_file
convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "/opt/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
obj.parse(doc.getroot(), mode=mode)
File "/opt/odoo/openerp/tools/convert.py", line 801, in parse
self.parse(rec, mode)
File "/opt/odoo/openerp/tools/convert.py", line 804, in parse
self._tags[rec.tag](self.cr, rec, de, mode=mode)
File "/opt/odoo/openerp/tools/convert.py", line 708, in _tag_record
id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1142, in _update
res_id = model_obj.create(cr, uid, values, context=context)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, _args, *_kwargs)
File "/opt/odoo/openerp/api.py", line 354, in old_api
result = method(recs, _args, *_kwargs)
File "/opt/odoo/openerp/models.py", line 4150, in create
record = self.browse(self._create(old_vals))
File "/opt/odoo/openerp/api.py", line 248, in wrapper
return new_api(self, _args, *_kwargs)
File "/opt/odoo/openerp/api.py", line 490, in new_api
result = method(self._model, cr, uid, _args, *_old_kwargs)
File "/opt/odoo/openerp/models.py", line 4288, in _create
tuple([u[2] for u in updates if len(u) > 2])
File "/opt/odoo/openerp/sql_db.py", line 141, in wrapper
return f(self, _args, *_kwargs)
File "/opt/odoo/openerp/sql_db.py", line 220, in execute
res = self._obj.execute(query, params)
ParseError: "el valor null para la columna \xabaction_id\xbb viola la restricci\xf3n not null
DETALLE: La fila que falla contiene (296, 2016-05-13 20:12:03.929191, null, 10, 1, null, open, 2016-05-13 20:12:03.929191, manual, 1, null).
" while parsing /opt/odoo/addons/l10n_cl_chart/data/l10n_cl_bmya_wizard.xml:4, near
<record id="account.action_wizard_multi_chart_todo" model="ir.actions.todo">
<field name="state">open</field>
</record>

**Comment by Danisan** [comment]
Estimado, este issue, ya fué reportado. (#2) por este motivo, voy a cerrar el mismo. Incluyo link con las recomendaciones de colaboración. http://www.odoochile.org/blog/novedades-1/post/principios-para-colaborar-en-github-1#blog_content
